set_property SRC_FILE_INFO {cfile:/home/chamdoo/NDPSql/platform/build_tools/connectal/out/vcu108/aurora_8b10b_fmc1/ip_0/synth/aurora_8b10b_fmc1_gt.xdc rfile:../../../../platform/build_tools/connectal/out/vcu108/aurora_8b10b_fmc1/ip_0/synth/aurora_8b10b_fmc1_gt.xdc id:1 order:EARLY scoped_inst:inst/gt_wrapper_i/aurora_8b10b_fmc1_gt_i/inst} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y20 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[5].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y21 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[5].*gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y22 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[5].*gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y23 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[5].*gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST}]
